title: endoflife.date
url: https://endoflife.date
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-timeago
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jemoji
exclude:
  - .idea
  - _auto
  - CODE-OF-CONDUCT.md
  - Gemfile
  - Gemfile.lock
  - HACKING.md
  - LICENSE
  - netlify.toml
  - node_modules
  - package.json
  - package-lock.json
  - vendor/
  - Rakefile
  - README.md
  - requirements.txt
  - runtime.txt
include:
  - _redirects
  - _headers
# Theme Documentation: https://pmarsceill.github.io/just-the-docs/
theme: just-the-docs
nav_sort: case_insensitive
search_enabled: true
# These links show up on the top
aux_links:
  recommendations:
    - /recommendations
  contribute:
    - /contribute
  source:
    - https://github.com/endoflife-date/endoflife.date
  api:
    - /docs/api
jekyll_timeago:
  # Use 2 terms in relative timestamps:
  # [YES] x years, y months
  # [YES] x months, z weeks
  # [NO] x years, y months, z days
  depth: 2
  # Give approx times in relative time
  # within a 10% error margin
  # See https://github.com/markets/jekyll-timeago/pull/24
  # for what this does
  threshold: 0.1
# Cause a build to fail if there is a YAML syntax error in a page's front matter.  (#40)
strict_front_matter: true
defaults:
  - scope:
      path: ""
    values:
      image: /assets/logo-512x512.png
  - scope:
      path: "products"
    values:
      layout: product
      releaseCycleColumn: true
      releaseDateColumn: false
      discontinuedColumn: false
      activesupportColumn: false
      eolColumn: true
      columns:
        # The spaces before Yes/No
        # are intentional to avoid the
        # YAML norway problem
        support:
          if: activeSupportColumn
          type: date
          defaults:
            on-true:
              text: " Yes"
              color: green
            on-false:
              text: " No"
              color: red
        eol:
          if: eolColumn
          type: date
          defaults:
            on-false:
              text: " Yes"
              color: green
            on-true:
              text: " No"
              color: red

      releaseColumn: true
encoding: utf-8
colorClass:
  green: bg-green-000
  red: bg-red-000
  yellow: bg-yellow-200
